language: go
go:
  - "1.10"
  
# before_cache:
# -  find $GOPATH/pkg/**/github.com/vjeantet/bitfan/* -maxdepth 0 ! -name vendor -print0 | xargs -0 rm -rf
# 
# cache:
#   directories:
#     - $GOPATH/pkg
   
install:
    - go get -v golang.org/x/tools/cmd/cover
    - go get -v github.com/stretchr/testify/assert
    - go get -v github.com/smartystreets/goconvey
    - go get -v github.com/miekg/dns
    - go get -v github.com/segmentio/kafka-go
script:
    - ./go.test.sh
after_success:
    - bash <(curl -s https://codecov.io/bash)
    - test -n "$TRAVIS_TAG" && curl -sL http://git.io/goreleaser | bash
